import "../assets/styles/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { auth } from "@/auth";
import AuthProvider from "@/components/providers/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: process.env.APP_NAME ?? "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{children: React.ReactNode;}>) {
  const session = await auth()  
  return (
    <html lang="en" className="h-full bg-white dark:bg-gray-600" data-theme="light">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full"`} suppressHydrationWarning={true}>
        <AuthProvider session={session}>
        {children}
        </AuthProvider>
      </body>
    </html>
  );
}
